log_dir: /Users/syu/project/ml/ai_chat/mcp_agent/logs
mcp_model:
  api_key: sk-fadb6690a1144f16b9212266a4e2d666
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: deepseek-v3.2
  skills_path: skills_bqm
  compatible_url: http://127.0.0.1:7001/stream
  models:
    - model: DeepSeekV3
      thinking: true
      search: false
      type: DeepSeek
      modelName: deepseek-v3.2
      alias: from_ali_nothinking
    - model: DeepSeekR1
      thinking: true
      search: false
      type: DeepSeek
      modelName: deepseek-r1
      alias: from_ali
    - model: QwenMax
      thinking: true
      search: false
      type: Qwen
      modelName: qwen-max-latest
      alias: from_ali
    - model: Qwen235bA22b
      thinking: true
      search: false
      type: Qwen
      modelName: qwen3-235b-a22b
      alias: from_ali
    - model: Qwen35
      thinking: true
      search: true
      type: Qwen
      modelName: qwen3.5-plus
      alias: from_ali
    - model: MiniMax-M2.5
      thinking: true
      search: false
      type: MiniMax
      modelName: MiniMax-M2.5
      alias: from_minimaxi_for_openai
    - model: glm-5
      thinking: true
      search: false
      type: GLM
      modelName: glm-5
      alias: from_ali
    - model: kimi-k2.5
      thinking: true
      search: false
      type: Kimi
      modelName: kimi-k2.5
      alias: from_ali
    - model: Elephant
      thinking: true
      search: false
      type: OpenRouter
      modelName: openrouter/elephant-alpha
      alias: from_openrouter
datasource:
  host: 49.4.55.222
  port: 3306
  user: bqm
  password: '_s7hP@HG7(ZL!PEXaw'
  database: bqm

postgres:
  host: 49.4.13.146
  port: 5432
  user: bqm
  password: '_s7hP@HG7(ZL!PEXaw'
  database: bqm

oss:
  url: http://www.51bqm.com:9001
  endpoint: http://www.51bqm.com:9000
  access_key: admin
  secret_key: n7d3t7x7
  bucket_name: mcp
