log_dir: /Users/syu/project/ml/ai_chat/mcp_agent/logs
mcp_model:
  api_key: sk-fadb6690a1144f16b9212266a4e2d666
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: deepseek-v3.2
  skills_path: skills
  compatible_url: https://www.ufoyy.top:7022/stream
  compatible_model_map:
    deepseek-v3.2: from_ali_nothinking
    deepseek-r1: from_ali
    qwen-max-latest: from_ali
    qwen3.5-plus: from_ali
    qwen3-235b-a22b: from_ali
    MiniMax-M2.5: from_ali
    glm-5: from_ali
    kimi-k2.5: from_ali
datasource:
  host: 74.48.18.221
  port: 3306
  user: root
  password: 'LW56wii3g7qGf71ZCA'
  database: app

postgres:
  host: 74.48.18.221
  port: 5432
  user: syu
  password: 'LW56wii3g7qGf71ZCA'
  database: app

oss:
  endpoint: https://www.ufoyy.top:9000
  access-key: admin
  secret-key: n7d3t7x7
  bucket-name: mcp