log_dir: /Users/syu/project/ml/ai_chat/mcp_agent/logs
mcp_model:
  api_key: sk-fadb6690a1144f16b9212266a4e2d666
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: deepseek-v3.2
  skills_path: skills_bqm
  compatible_url: http://www.51bqm.com:8086/stream
  compatible_model_map:
    deepseek-v3.2: from_ali_nothinking
    deepseek-r1: from_ali
    qwen-max-latest: from_ali
    qwen3.5-plus: from_ali
    qwen3-235b-a22b: from_ali
    MiniMax-M2.5: from_ali
    glm-5: from_ali
    kimi-k2.5: from_ali
datasource:
  host: 49.4.55.222
  port: 3306
  user: bqm
  password: '_s7hP@HG7(ZL!PEXaw'
  database: bqm

postgres:
  host: 49.4.13.146
  port: 5432
  user: bqm
  password: '_s7hP@HG7(ZL!PEXaw'
  database: bqm

oss:
  url: http://www.51bqm.com:9001
  endpoint: http://www.51bqm.com:9000
  access_key: admin
  secret_key: n7d3t7x7
  bucket_name: mcp
