log_dir: /Users/syu/project/ml/ai_chat/mcp_agent/logs
mcp_model:
  skills_path: skills_chat
  compatible_url: https://www.ufoyy.top:7022/stream
  models:
    - model: DeepSeekV4Flash
      thinking: true
      search: false
      type: DeepSeek
      modelName: deepseek-v4-flash
      alias: from_deepseek
    - model: DeepSeekV4Pro
      thinking: true
      search: false
      type: DeepSeek
      modelName: deepseek-v4-pro
      alias: from_deepseek
datasource:
  host: 192.129.246.232
  port: 3306
  user: root
  password: 'LW56wii3g7qGf71ZCA'
  database: app

postgres:
  host: 192.129.246.232
  port: 5432
  user: syu
  password: 'LW56wii3g7qGf71ZCA'
  database: app

oss:
  endpoint: https://www.ufoyy.top:9000
  access-key: admin
  secret-key: n7d3t7x7
  bucket-name: mcp