[project]
name = "mcp-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "boto3>=1.42.24",
    "dashscope>=1.25.12",
    "dependency-injector>=4.48.2",
    "fastapi>=0.117.1",
    "langchain>=1.2.7",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.7",
    "langchain-openai>=1.1.7",
    "langgraph>=1.0.7",
    "langgraph-checkpoint-postgres>=3.0.4",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "loguru>=0.7.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "psycopg-binary>=3.3.2",
    "psycopg-pool>=3.2.0",
    "pymysql>=1.1.2",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "skillkit>=0.4.0",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.36.0",
    "langchain-deepseek",
    "langchain-ollama>=1.0.1",
]
